languages:
  default_source: auto
  default_target: tr
  supported_source:
  - auto
  - en
  - tr
  - de
  - fr
  - es
  - ru
  - ar
  - zh
  supported_target:
  - tr
  - en
  - de
  - fr
  - es
  - ru
  - ar
  - zh
ocr:
  cache_timeout: 5
  preferred_engine: Tesseract
shortcuts:
  global_enabled: false
theme:
  mode: dark
translation:
  auto_copy: false
  engine: Google Translate
  preferred_engine: Local API
  refresh_rate: 0.5
translation_opacity: 0.9
